tweaks to snakejob

diff --git a/snakejob b/snakejob
--- a/snakejob
+++ b/snakejob
@@ -19,6 +19,45 @@ else
 
 fi
 
+# use bash getopt to use short flags
+config='config.yaml'
+snakefile='Snakefile'
+dryrun=""
+
+print_usage() {
+  printf "Usage: ./snakejob [-h] [-c] config.yaml [-s] Snakefile\nOptions:\n\t-c config file\n\t-s Snakefile\n\t-n dry run mode\n"
+}
+
+while getopts 'c:s:nh' flag; do
+  case "${flag}" in
+    c) config="${OPTARG}" ;;
+    s) snakefile="${OPTARG}" ;;
+    n) dryrun="-n" ;;
+    h) print_usage
+       exit 1 ;;
+  esac
+done
+
+
+echo config used is $config
+echo snakefile used is $snakefile
+
+if [ ! -z "$dryrun" ];then
+	echo "dry run mode"
+fi
+
+if [ ! -e $config ]; then
+	echo "error: config file does not exist" 
+	exit 0
+fi
+
+if [ ! -e $snakefile ]; then
+	echo "error: snakefile does not exist"
+	exit 0
+fi
+
+#exit 0 
+
 bsub=("bsub -K -J $jname:{rule}:{wildcards}"
 "-P acc_als-omics "
 "-q {cluster.queue} "
@@ -30,5 +69,6 @@ bsub=("bsub -K -J $jname:{rule}:{wildcards}"
 snakemake -u cluster.yaml --cluster-sync "${bsub[*]}" \
   --local-cores 4 --max-jobs-per-second 5 \
   --jobs 100 \
-  -s Snakefile --configfile $config_file
+  -s $snakefile --configfile $config \
+  $dryrun
 
